<?php
/**
 * @license Copyright 2011-2014 BitPay Inc., MIT License
 * @see https://github.com/bitpay/magento-plugin/blob/master/LICENSE
 */
?>
<?php
/**
 * @see Bitpay_Core_Block_Form_Bitpay
 */
?>
<?php $_code = $this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        When paying with this payment method, once you click on the `Place Order` button
        you will be transfered to <a href="https://bitpay.com" target="_new">BitPay</a>
        to complete your purchase.
    </li>
</ul>
