<?php
/**
 * @license Copyright 2011-2016 BitPay Inc., MIT License
 * @see https://github.com/bitpay/magento-plugin/blob/master/LICENSE
 */

$url = $this->getIframeUrl();
switch($url) {
    case 'notbitpay':
        break; // customer is using another payment method
    case 'paid':
        echo 'Order payment received.  Place Order to complete.';
        break;
    case 'disabled':
        echo 'Please click Place Order to continue to bitpay.com.';
        break;
    case false:
        echo 'Error creating invoice.  Please try again or try another payment solution.';
        break;
    default:
        echo '<iframe class="bitpay_invoice_iframe" src="'.$url.'" style="width:500px; height:150px; overflow:hidden; border:none; margin:auto; display:none;" scrolling="no" allowtransparency="true" frameborder="0"> </iframe>';
        break;
}
$quoteId = $this->getQuote()->getId();
$request = Mage::app()->getRequest();
$url     = Mage::getUrl('bitpay/index/index/');
if ($request->getScheme() == 'https') {
    $url = str_replace('http://', 'https://', $url);
}

?>
<script type="text/javascript">
//<![CDATA[
if ($$('iframe.bitpay_invoice_iframe').length > 0) {
  var bpListener = {
    nextStep: function(transport) {
      if (transport && transport.responseText) {
        try{
          response = eval('(' + transport.responseText + ')');
        }
        catch (e) {
          response = {};
        }
        if (response.success) {
          $$('iframe.bitpay_invoice_iframe')[0].setStyle({display:'block'});
          $$('button.btn-checkout')[0].setStyle({display:'none'});
          var ipnPoller = new PeriodicalExecuter(function() {
            new Ajax.Request("<?php echo $url . '?quote=' . $quoteId; ?>",
              {
                asynchronous: true,
                evalScripts: true,
                onComplete: function(request, json) {
                var data = request.responseText.evalJSON();
                if (data.paid) {
                  ipnPoller.stop();
                  review.nextStep(transport);
                }
              }
            });
          }, 5);
        } else {
          var msg = response.error_messages;
          if (typeof(msg)=='object') {
            msg = msg.join("\n");
          }
          if (msg) {
            alert(msg);
          }
        }
        if (response.update_section) {
          $('checkout-'+response.update_section.name+'-load').update(response.update_section.html);
        }
        if (response.goto_section) {
          checkout.gotoSection(response.goto_section, true);
        }
      }
    }
  };
  var reviewCheck = new PeriodicalExecuter(function() {
    if (review) {
      reviewCheck.stop();
      var originalSaveHandler = review.onSave;
      review.onSave = bpListener.nextStep.bindAsEventListener(review);
    }
  }, 1);
}
//]]>
</script>


