#!/usr/bin/env sh
####
#
# Script that removes old BitPay extension
#
rm -vrf app/code/community/Bitpay/Bitcoins
rm  -v app/design/frontend/base/default/layout/bitcoins.xml
rm -vrf app/etc/modules/Bitpay_Bitcoins.xml
rm -vrf lib/bitpay
rm -v shell/bitpay.php
