<?php 
/**
 * The MIT License (MIT)
 * 
 * Copyright (c) 2011-2014 BitPay LLC
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

$url = $this->GetIframeUrl();
switch($url)
{
case 'notbitpay':
    break; // customer is using another payment method
case 'paid':
    echo 'Order payment received.  Place Order to complete.';
    break;
case 'disabled':
    echo 'Please click Place Order to continue to bitpay.com.';
    break;
case false:
    echo 'Error creating invoice.  Please try again or try another payment solution.';
    break;
default:
    echo '<iframe src="'.$url.'" style="width:500px; height:150px; overflow:hidden; border:none; margin:auto; display:block;" scrolling="no" allowtransparency="true" frameborder="0"> </iframe>';
    break;
}
$quoteId = $this->GetQuoteId();
?>

<?php
$request = Mage::app()->getRequest();
$url     = Mage::getUrl('bitpay_callback/index/checkForPayment/');

if ($request->getScheme() == 'https')
{
	$url = str_replace('http://', 'https://', $url);
}
?>
<script type="text/javascript">
//<![CDATA[
new PeriodicalExecuter(function() {new Ajax.Request("<?php echo $url; ?>?quote=<?php echo $quoteId; ?>", {asynchronous:true, evalScripts:true, onComplete:function(request, json) {
	data = request.responseText.evalJSON(); 
	if (data.paid) { 
		buttons = $$("button.btn-checkout");
		buttons.each(function(btn) { btn.click(); })
	} 
}})}, 5);

//]]>
</script>
